### ISSUE TITLE
Pass Erddap URL by query parameter to allow for bookmarking

### ISSUE THREAD

**Issue by adamml** [hmedrano/erddap-status-dashboard#1]
Is it possible to structure the app to allow the dashboard to take a query parameter in the URL to allow the dashboard for a specific Erddap server instance to be bookmarked?

**Comment by hmedrano** [comment]
Sure!, the app now parses the query parameter `url`,  so just add it to the web app url, e.g.

https://share.streamlit.io/hmedrano/erddap-status-dashboard/main/dashboard_streamlit_app.py?url=https://erddap.marine.ie/erddap

**Comment by adamml** [comment]
Thanks!!
